# Generated by Django 5.0.4 on 2024-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coworking', models.BigIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoworkingSpaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.BigIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('date_start', models.TimeField()),
                ('date_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coworking', models.BigIntegerField()),
                ('file', models.FileField(upload_to='upldfile/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coworking', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('num_of_seats', models.BigIntegerField(null=True)),
            ],
        ),
    ]
