# Generated by Django 5.0.4 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookings_businesses_coworkingspaces_images_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspaces',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='upldfile/'),
        ),
        migrations.AlterField(
            model_name='coworkingspaces',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
