# Generated by Django 4.1.4 on 2024-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coworkingspaces_rating_services_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upldfile/'),
        ),
    ]
