# Generated by Django 5.0.4 on 2024-05-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_businesses_id_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspaces',
            name='coworking_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
