# Generated by Django 5.0.4 on 2024-05-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_businesses_img_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id_coworking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coworkingspaces'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AlterField(
            model_name='coworkingspaces',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.businesses'),
        ),
        migrations.AlterField(
            model_name='images',
            name='id_coworking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coworkingspaces'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_coworking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coworkingspaces'),
        ),
    ]
