# Generated by Django 5.0.4 on 2024-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bookings_id_coworking_alter_bookings_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspaces',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
