# Generated by Django 5.0.4 on 2024-05-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_bookings_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user_rating',
        ),
    ]
