# Generated by Django 5.0.4 on 2024-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_bookings_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworkingspaces',
            name='rating',
        ),
        migrations.AddField(
            model_name='bookings',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coworkingspaces',
            name='rating_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coworkingspaces',
            name='rating_sum',
            field=models.BigIntegerField(default=0),
        ),
    ]
