# Generated by Django 5.0.4 on 2024-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_coworkingspaces_rating_bookings_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, upload_to='upldfile/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='num_of_seats',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
