# Generated by Django 5.0.4 on 2024-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_services_img_alter_services_num_of_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, max_length=200, upload_to='upldfile/'),
        ),
    ]
