# Generated by Django 5.0.4 on 2024-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_services_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingspaces',
            name='benefits',
            field=models.JSONField(default={'coffe': False, 'fruits': False, 'kitchen': False, 'locker': False, 'parking': False, 'printer': False, 'wifi': False}),
        ),
    ]
