# Generated by Django 5.0.4 on 2024-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_coworkingspaces_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspaces',
            name='benefits',
            field=models.JSONField(default={'coffe': False, 'fitness': False, 'fruits': False, 'kitchen': False, 'locker': False, 'parking': False, 'printer': False, 'wifi': False}),
        ),
    ]
